############################
# System utilities
############################
SYSTEM_UTILS=(
  btop
  fastfetch
  fzf
  zip
  unzip
  wget
  curl
  firefox
  ripgrep
  bat
  lsof
  strace
  tar
)

############################
# Development tools
############################
DEV_TOOLS=(
  git
  neovim
  vim
  kitty
  yazi
  fd
  tree-sitter
  python
  lua
  python-pip
  luarocks
  asdf-vm
  wl-clipboard
  lazygit
  lazydocker
  stow
  gcc
  make
  fd
  nodejs
  npm
)

############################
# GUI utilities / daily use
############################
UTILS=(
  qalculate-gtk      # calculadora GUI
  gnome-disk-utility # gerenciar discos
  baobab             # uso de disco
  file-roller        # compactação GUI
  gvfs
  gvfs-mtp
  gvfs-smb
  ntfs-3g
)

############################
# File manager (GUI)
############################
FILE_MANAGERS=(
  thunar
  thunar-archive-plugin
  thunar-volman
)

############################
# Audio / Video
############################
AUDIO_VIDEO=(
  pavucontrol
  playerctl
  mpv
)

############################
# Screenshots / Recording (Wayland)
############################
SCREEN=(
  grim
  slurp
  swappy
  wf-recorder
)

############################
# UX / Wayland helpers
############################
UX=(
  mako
  wlogout
  brightnessctl
)

############################
# Desktop / Bar
############################
DESKTOP=(
  waybar
)

############################
# Fonts
############################
FONTS=(
  noto-fonts
  noto-fonts-emoji
  ttf-jetbrains-mono-nerd
  ttf-dejavu
  ttf-liberation
)

############################
# Network
############################
NETWORK=(
  network-manager-applet
  inetutils
  bind
)

############################
# Services to enable
############################
SERVICES=(
  NetworkManager.service
)
