# System utilities
SYSTEM_UTILS=(
  btop
  lazygit
  lazydocker
  stow
  fastfetch
  fzf
  zip
  unzip
  wget
  curl
  firefox
)

# Development tools
DEV_TOOLS=(
  vim
  yazi
  zsh
  neovim
  tmux
  ghostty
  kitty
  git
  asdf-vm
  luarocks
  fd
  tree-sitter
  python-pip
)

# System maintenance
MAINTENANCE=(
)

# Window manager
DESKTOP=(
    hyprland
    hyprpaper
    waybar
)

# Media packages
MEDIA=(
)

# Fonts
FONTS=(
  noto-fonts
  noto-fonts-emoji
  ttf-jetbrains-mono-nerd
)

# Services to enable
SERVICES=(
  gdm.service
  NetworkManager.service
)
