# preload = /home/samuel/wallpapers/anime/aurora_boreal.png
preload = /home/samuel/wallpapers/japan.png

wallpaper {
    monitor = eDP-1
    path = /home/samuel/wallpapers/japan.png
    fit_mode = cover
}

#enable splash text rendering over the wallpaper (default true)
splash = false

#fully disable ipc (default true)
# ipc = off

