# preload = /home/samuel/Pictures/wallpapers/anime/aurora_boreal.png
# preload = /home/samuel/Pictures/wallpapers/anime/lake_and_mountains.jpg

wallpaper {
    monitor = DP-1
    path = /home/samuel/wallpapers/lake_and_mountains.jpg
    fit_mode = cover
}

#enable splash text rendering over the wallpaper (default true)
splash = false

#fully disable ipc (default true)
# ipc = off

