preload = /home/samuel/Pictures/wallpapers/anime/aurora_boreal.png
preload = /home/samuel/Pictures/wallpapers/anime/lake_and_mountains.jpg

wallpaper = ,/home/samuel/Pictures/wallpapers/anime/lake_and_mountains.jpg
# wallpaper = monitor1,/path/to/image.png
# wallpaper = monitor2,/path/to/next_image.png
# .. more monitors

#enable splash text rendering over the wallpaper
# splash = true

#fully disable ipc
# ipc = off

