theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes = true
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["diagnostics"]
right = ["position", "file-type"]

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true

[keys.normal]
"C-s" = ":wa"
"C-q" = ":q"
"C-x" = ":wq"

[keys.normal.space]
"=" = ":format"
