# YAML
[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

# TOML
[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]
